### ISSUE TITLE
Err when setting up ip.

### ISSUE THREAD

**Issue by wzqvip** [MrFlacko/lancache-script#3]
When I put it under my router and set 192.168.x.x, it succeeds, but when I just Connect it to the internet and got an ip like 10.19.x.x, and I set it, err occurred.

```Recreating lancache_dns_1                     ...

ERROR: for 776f574f2600_lancache_monolithic_1  a bytes-like object is required, not 'str'
```

`Removing lancache_monolithic_1
Recreating 776f574f2600_lancache_monolithic_1 ...
Recreating lancache_dns_1                     ...

ERROR: for 776f574f2600_lancache_monolithic_1  a bytes-like object is required, not 'str'

Recreating lancache_dns_1                     ... error

ERROR: for lancache_dns_1  b'cannot stop container: 6a5950ad45e96ea82be321bbd3bdd87f0cc97205643029ff1f526d80681d206b: permission denied'

ERROR: for monolithic  a bytes-like object is required, not 'str'

ERROR: for dns  b'cannot stop container: 6a5950ad45e96ea82be321bbd3bdd87f0cc97205643029ff1f526d80681d206b: permission denied'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/01a9b706c0297a1906fef10be7d8f8e0ce19c95244442ddece02bde13496b4f0/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b"error while creating mount source path '/var/lib/lancache/lancache/cache': mkdir /var/lib/lancache: read-only file system"")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 561, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 486, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 481, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 602, in recreate_container
    self.start_container(new_container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
`

**Comment by MrFlacko** [comment]
Very weird error it shouldn't be giving this error. Did you manage to get it working?

**Comment by wzqvip** [comment]
> Very weird error it shouldn't be giving this error. Did you manage to get it working?

Steam support Lan cache now, so I just didn't dig deeper.
